var files_dup =
[
    [ "adminselectwindow.cpp", "adminselectwindow_8cpp.html", null ],
    [ "adminselectwindow.h", "adminselectwindow_8h.html", "adminselectwindow_8h" ],
    [ "adminwindow.cpp", "adminwindow_8cpp.html", null ],
    [ "adminwindow.h", "adminwindow_8h.html", "adminwindow_8h" ],
    [ "arizonainput.cpp", "arizonainput_8cpp.html", null ],
    [ "arizonainput.h", "arizonainput_8h.html", "arizonainput_8h" ],
    [ "arizonawindow.cpp", "arizonawindow_8cpp.html", null ],
    [ "arizonawindow.h", "arizonawindow_8h.html", "arizonawindow_8h" ],
    [ "custominput.cpp", "custominput_8cpp.html", null ],
    [ "custominput.h", "custominput_8h.html", "custominput_8h" ],
    [ "customwindow.cpp", "customwindow_8cpp.html", null ],
    [ "customwindow.h", "customwindow_8h.html", "customwindow_8h" ],
    [ "irvinewindow.cpp", "irvinewindow_8cpp.html", null ],
    [ "irvinewindow.h", "irvinewindow_8h.html", "irvinewindow_8h" ],
    [ "main.cpp", "main_8cpp.html", "main_8cpp" ],
    [ "mainwindow.cpp", "mainwindow_8cpp.html", null ],
    [ "mainwindow.h", "mainwindow_8h.html", "mainwindow_8h" ],
    [ "plantripwindow.cpp", "plantripwindow_8cpp.html", null ],
    [ "plantripwindow.h", "plantripwindow_8h.html", "plantripwindow_8h" ],
    [ "saddlebacktripwindow.cpp", "saddlebacktripwindow_8cpp.html", "saddlebacktripwindow_8cpp" ],
    [ "saddlebacktripwindow.h", "saddlebacktripwindow_8h.html", "saddlebacktripwindow_8h" ],
    [ "summarypage.cpp", "summarypage_8cpp.html", null ],
    [ "summarypage.h", "summarypage_8h.html", "summarypage_8h" ],
    [ "travelplan.cpp", "travelplan_8cpp.html", null ],
    [ "travelplan.h", "travelplan_8h.html", "travelplan_8h" ],
    [ "welcomewindow.cpp", "welcomewindow_8cpp.html", null ],
    [ "welcomewindow.h", "welcomewindow_8h.html", "welcomewindow_8h" ]
];